// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5erKeB2HbDQVCIysn0ktG3e8kKjA7cdI',
    appId: '1:15606020851:web:dfc09361ca524ac6d65586',
    messagingSenderId: '15606020851',
    projectId: 'responsible-map-388106',
    authDomain: 'responsible-map-388106.firebaseapp.com',
    storageBucket: 'responsible-map-388106.appspot.com',
    measurementId: 'G-S6364FL8K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANKqNDv6MgUQEmXE-j2WZmmbkntWddrAg',
    appId: '1:15606020851:android:52ea9e4b7ddeaf67d65586',
    messagingSenderId: '15606020851',
    projectId: 'responsible-map-388106',
    storageBucket: 'responsible-map-388106.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAscOfrnHpYRNxGGAvPc5zHEw2H2exvlII',
    appId: '1:15606020851:ios:9d5deec88b27db80d65586',
    messagingSenderId: '15606020851',
    projectId: 'responsible-map-388106',
    storageBucket: 'responsible-map-388106.appspot.com',
    iosBundleId: 'com.example.souvenirShop',
  );
}
